-- WC2026 Seed Data
-- 48 teams, 12 groups (A-L), 72 group stage matches

INSERT INTO teams (name, country_code, group_name, flag_emoji) VALUES
  ('Mexico', 'MEX', 'A', '🇲🇽'),
  ('South Africa', 'RSA', 'A', '🇿🇦'),
  ('South Korea', 'KOR', 'A', '🇰🇷'),
  ('Czech Republic', 'CZE', 'A', '🇨🇿'),
  ('Canada', 'CAN', 'B', '🇨🇦'),
  ('Bosnia and Herzegovina', 'BIH', 'B', '🇧🇦'),
  ('Qatar', 'QAT', 'B', '🇶🇦'),
  ('Switzerland', 'SUI', 'B', '🇨🇭'),
  ('Brazil', 'BRA', 'C', '🇧🇷'),
  ('Morocco', 'MAR', 'C', '🇲🇦'),
  ('Haiti', 'HAI', 'C', '🇭🇹'),
  ('Scotland', 'SCO', 'C', '🏴󠁧󠁢󠁳󠁣󠁴󠁿'),
  ('United States', 'USA', 'D', '🇺🇸'),
  ('Paraguay', 'PRY', 'D', '🇵🇾'),
  ('Australia', 'AUS', 'D', '🇦🇺'),
  ('Türkiye', 'TUR', 'D', '🇹🇷'),
  ('Germany', 'GER', 'E', '🇩🇪'),
  ('Curaçao', 'CUW', 'E', '🇨🇼'),
  ('Ivory Coast', 'CIV', 'E', '🇨🇮'),
  ('Ecuador', 'ECU', 'E', '🇪🇨'),
  ('Netherlands', 'NED', 'F', '🇳🇱'),
  ('Japan', 'JPN', 'F', '🇯🇵'),
  ('Sweden', 'SWE', 'F', '🇸🇪'),
  ('Tunisia', 'TUN', 'F', '🇹🇳'),
  ('Belgium', 'BEL', 'G', '🇧🇪'),
  ('Egypt', 'EGY', 'G', '🇪🇬'),
  ('Iran', 'IRN', 'G', '🇮🇷'),
  ('New Zealand', 'NZL', 'G', '🇳🇿'),
  ('Spain', 'ESP', 'H', '🇪🇸'),
  ('Cape Verde', 'CPV', 'H', '🇨🇻'),
  ('Saudi Arabia', 'KSA', 'H', '🇸🇦'),
  ('Uruguay', 'URU', 'H', '🇺🇾'),
  ('France', 'FRA', 'I', '🇫🇷'),
  ('Senegal', 'SEN', 'I', '🇸🇳'),
  ('Iraq', 'IRQ', 'I', '🇮🇶'),
  ('Norway', 'NOR', 'I', '🇳🇴'),
  ('Argentina', 'ARG', 'J', '🇦🇷'),
  ('Algeria', 'ALG', 'J', '🇩🇿'),
  ('Austria', 'AUT', 'J', '🇦🇹'),
  ('Jordan', 'JOR', 'J', '🇯🇴'),
  ('Portugal', 'POR', 'K', '🇵🇹'),
  ('DR Congo', 'COD', 'K', '🇨🇩'),
  ('Uzbekistan', 'UZB', 'K', '🇺🇿'),
  ('Colombia', 'COL', 'K', '🇨🇴'),
  ('England', 'ENG', 'L', '🏴󠁧󠁢󠁥󠁮󠁧󠁿'),
  ('Croatia', 'CRO', 'L', '🇭🇷'),
  ('Ghana', 'GHA', 'L', '🇬🇭'),
  ('Panama', 'PAN', 'L', '🇵🇦');

INSERT INTO matches (home_team_id, away_team_id, round_id, match_datetime, venue, status) VALUES
  ((SELECT id FROM teams WHERE country_code = 'MEX'), (SELECT id FROM teams WHERE country_code = 'RSA'), 'group_stage', '2026-06-12T00:00:00Z', 'Mexico City Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'KOR'), (SELECT id FROM teams WHERE country_code = 'CZE'), 'group_stage', '2026-06-12T03:00:00Z', 'Estadio Guadalajara', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'CAN'), (SELECT id FROM teams WHERE country_code = 'BIH'), 'group_stage', '2026-06-12T07:00:00Z', 'Toronto Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'USA'), (SELECT id FROM teams WHERE country_code = 'PRY'), 'group_stage', '2026-06-12T10:00:00Z', 'Los Angeles Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'BRA'), (SELECT id FROM teams WHERE country_code = 'MAR'), 'group_stage', '2026-06-12T15:00:00Z', 'New York/New Jersey Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'HAI'), (SELECT id FROM teams WHERE country_code = 'SCO'), 'group_stage', '2026-06-13T06:00:00Z', 'Boston Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'AUS'), (SELECT id FROM teams WHERE country_code = 'TUR'), 'group_stage', '2026-06-13T09:00:00Z', 'BC Place Vancouver', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'QAT'), (SELECT id FROM teams WHERE country_code = 'SUI'), 'group_stage', '2026-06-14T00:00:00Z', 'San Francisco Bay Area Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'GER'), (SELECT id FROM teams WHERE country_code = 'CUW'), 'group_stage', '2026-06-14T05:00:00Z', 'Houston Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'NED'), (SELECT id FROM teams WHERE country_code = 'JPN'), 'group_stage', '2026-06-14T08:00:00Z', 'Dallas Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'CIV'), (SELECT id FROM teams WHERE country_code = 'ECU'), 'group_stage', '2026-06-14T11:00:00Z', 'Philadelphia Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'SWE'), (SELECT id FROM teams WHERE country_code = 'TUN'), 'group_stage', '2026-06-14T14:00:00Z', 'Estadio Monterrey', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'ESP'), (SELECT id FROM teams WHERE country_code = 'CPV'), 'group_stage', '2026-06-15T04:00:00Z', 'Miami Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'KSA'), (SELECT id FROM teams WHERE country_code = 'URU'), 'group_stage', '2026-06-15T07:00:00Z', 'Atlanta Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'BEL'), (SELECT id FROM teams WHERE country_code = 'EGY'), 'group_stage', '2026-06-15T10:00:00Z', 'Los Angeles Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'IRN'), (SELECT id FROM teams WHERE country_code = 'NZL'), 'group_stage', '2026-06-15T13:00:00Z', 'Seattle Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'FRA'), (SELECT id FROM teams WHERE country_code = 'SEN'), 'group_stage', '2026-06-16T03:00:00Z', 'New York/New Jersey Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'IRQ'), (SELECT id FROM teams WHERE country_code = 'NOR'), 'group_stage', '2026-06-16T06:00:00Z', 'Boston Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'ARG'), (SELECT id FROM teams WHERE country_code = 'ALG'), 'group_stage', '2026-06-16T09:00:00Z', 'Kansas City Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'AUT'), (SELECT id FROM teams WHERE country_code = 'JOR'), 'group_stage', '2026-06-17T00:00:00Z', 'San Francisco Bay Area Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'ENG'), (SELECT id FROM teams WHERE country_code = 'CRO'), 'group_stage', '2026-06-17T03:00:00Z', 'Toronto Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'GHA'), (SELECT id FROM teams WHERE country_code = 'PAN'), 'group_stage', '2026-06-17T06:00:00Z', 'Dallas Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'POR'), (SELECT id FROM teams WHERE country_code = 'COD'), 'group_stage', '2026-06-17T09:00:00Z', 'Houston Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'UZB'), (SELECT id FROM teams WHERE country_code = 'COL'), 'group_stage', '2026-06-17T15:00:00Z', 'Mexico City Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'CZE'), (SELECT id FROM teams WHERE country_code = 'RSA'), 'group_stage', '2026-06-18T03:00:00Z', 'Atlanta Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'SUI'), (SELECT id FROM teams WHERE country_code = 'BIH'), 'group_stage', '2026-06-18T06:00:00Z', 'Los Angeles Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'CAN'), (SELECT id FROM teams WHERE country_code = 'QAT'), 'group_stage', '2026-06-18T09:00:00Z', 'BC Place Vancouver', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'MEX'), (SELECT id FROM teams WHERE country_code = 'KOR'), 'group_stage', '2026-06-19T00:00:00Z', 'Estadio Guadalajara', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'BRA'), (SELECT id FROM teams WHERE country_code = 'HAI'), 'group_stage', '2026-06-19T05:30:00Z', 'Philadelphia Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'SCO'), (SELECT id FROM teams WHERE country_code = 'MAR'), 'group_stage', '2026-06-19T10:00:00Z', 'Boston Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'USA'), (SELECT id FROM teams WHERE country_code = 'AUS'), 'group_stage', '2026-06-20T00:00:00Z', 'Seattle Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'TUR'), (SELECT id FROM teams WHERE country_code = 'PRY'), 'group_stage', '2026-06-20T03:00:00Z', 'San Francisco Bay Area Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'NED'), (SELECT id FROM teams WHERE country_code = 'SWE'), 'group_stage', '2026-06-20T06:00:00Z', 'Houston Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'GER'), (SELECT id FROM teams WHERE country_code = 'CIV'), 'group_stage', '2026-06-20T09:00:00Z', 'Toronto Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'ECU'), (SELECT id FROM teams WHERE country_code = 'CUW'), 'group_stage', '2026-06-20T15:00:00Z', 'Kansas City Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'TUN'), (SELECT id FROM teams WHERE country_code = 'JPN'), 'group_stage', '2026-06-21T04:00:00Z', 'Estadio Monterrey', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'ESP'), (SELECT id FROM teams WHERE country_code = 'KSA'), 'group_stage', '2026-06-21T07:00:00Z', 'Atlanta Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'URU'), (SELECT id FROM teams WHERE country_code = 'CPV'), 'group_stage', '2026-06-21T10:00:00Z', 'Miami Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'BEL'), (SELECT id FROM teams WHERE country_code = 'IRN'), 'group_stage', '2026-06-21T15:00:00Z', 'Los Angeles Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'NZL'), (SELECT id FROM teams WHERE country_code = 'EGY'), 'group_stage', '2026-06-22T04:00:00Z', 'BC Place Vancouver', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'FRA'), (SELECT id FROM teams WHERE country_code = 'IRQ'), 'group_stage', '2026-06-22T07:00:00Z', 'New York/New Jersey Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'NOR'), (SELECT id FROM teams WHERE country_code = 'SEN'), 'group_stage', '2026-06-22T10:00:00Z', 'Philadelphia Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'ARG'), (SELECT id FROM teams WHERE country_code = 'AUT'), 'group_stage', '2026-06-23T00:00:00Z', 'Dallas Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'JOR'), (SELECT id FROM teams WHERE country_code = 'ALG'), 'group_stage', '2026-06-23T03:00:00Z', 'San Francisco Bay Area Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'POR'), (SELECT id FROM teams WHERE country_code = 'UZB'), 'group_stage', '2026-06-23T06:00:00Z', 'Houston Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'ENG'), (SELECT id FROM teams WHERE country_code = 'GHA'), 'group_stage', '2026-06-23T09:00:00Z', 'Boston Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'PAN'), (SELECT id FROM teams WHERE country_code = 'CRO'), 'group_stage', '2026-06-23T13:00:00Z', 'Toronto Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'COL'), (SELECT id FROM teams WHERE country_code = 'COD'), 'group_stage', '2026-06-24T04:00:00Z', 'Houston Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'SCO'), (SELECT id FROM teams WHERE country_code = 'BRA'), 'group_stage', '2026-06-24T07:00:00Z', 'Miami Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'MAR'), (SELECT id FROM teams WHERE country_code = 'HAI'), 'group_stage', '2026-06-24T10:00:00Z', 'Atlanta Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'CAN'), (SELECT id FROM teams WHERE country_code = 'SUI'), 'group_stage', '2026-06-25T00:00:00Z', 'Vancouver Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'BIH'), (SELECT id FROM teams WHERE country_code = 'QAT'), 'group_stage', '2026-06-25T03:00:00Z', 'Seattle Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'MEX'), (SELECT id FROM teams WHERE country_code = 'CZE'), 'group_stage', '2026-06-25T06:00:00Z', 'Mexico City Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'KOR'), (SELECT id FROM teams WHERE country_code = 'RSA'), 'group_stage', '2026-06-25T09:00:00Z', 'Estadio Monterrey', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'ECU'), (SELECT id FROM teams WHERE country_code = 'GER'), 'group_stage', '2026-06-25T15:00:00Z', 'Philadelphia Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'CUW'), (SELECT id FROM teams WHERE country_code = 'CIV'), 'group_stage', '2026-06-26T04:00:00Z', 'New York/New Jersey Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'TUN'), (SELECT id FROM teams WHERE country_code = 'NED'), 'group_stage', '2026-06-26T07:00:00Z', 'Dallas Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'JPN'), (SELECT id FROM teams WHERE country_code = 'SWE'), 'group_stage', '2026-06-26T10:00:00Z', 'Houston Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'USA'), (SELECT id FROM teams WHERE country_code = 'TUR'), 'group_stage', '2026-06-26T15:00:00Z', 'Los Angeles Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'PRY'), (SELECT id FROM teams WHERE country_code = 'AUS'), 'group_stage', '2026-06-27T04:00:00Z', 'San Francisco Bay Area Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'NOR'), (SELECT id FROM teams WHERE country_code = 'FRA'), 'group_stage', '2026-06-27T07:00:00Z', 'Boston Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'SEN'), (SELECT id FROM teams WHERE country_code = 'IRQ'), 'group_stage', '2026-06-27T10:00:00Z', 'Toronto Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'NZL'), (SELECT id FROM teams WHERE country_code = 'BEL'), 'group_stage', '2026-06-27T15:00:00Z', 'Seattle Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'EGY'), (SELECT id FROM teams WHERE country_code = 'IRN'), 'group_stage', '2026-06-28T04:00:00Z', 'Los Angeles Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'URU'), (SELECT id FROM teams WHERE country_code = 'ESP'), 'group_stage', '2026-06-28T07:00:00Z', 'Houston Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'CPV'), (SELECT id FROM teams WHERE country_code = 'KSA'), 'group_stage', '2026-06-28T10:00:00Z', 'Guadalajara Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'PAN'), (SELECT id FROM teams WHERE country_code = 'ENG'), 'group_stage', '2026-06-28T15:00:00Z', 'New York/New Jersey Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'CRO'), (SELECT id FROM teams WHERE country_code = 'GHA'), 'group_stage', '2026-06-29T04:00:00Z', 'Philadelphia Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'JOR'), (SELECT id FROM teams WHERE country_code = 'ARG'), 'group_stage', '2026-06-29T07:00:00Z', 'Kansas City Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'ALG'), (SELECT id FROM teams WHERE country_code = 'AUT'), 'group_stage', '2026-06-29T10:00:00Z', 'Dallas Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'COL'), (SELECT id FROM teams WHERE country_code = 'POR'), 'group_stage', '2026-06-29T15:00:00Z', 'Miami Stadium', 'SCHEDULED'),
  ((SELECT id FROM teams WHERE country_code = 'COD'), (SELECT id FROM teams WHERE country_code = 'UZB'), 'group_stage', '2026-06-30T04:00:00Z', 'Atlanta Stadium', 'SCHEDULED');

SELECT COUNT(*) AS total_teams FROM teams;
SELECT COUNT(*) AS total_matches FROM matches;
